@startuml
class "Event" as Event
class "Conference" as Conference
class "BoardMeeting" as BoardMeeting
class "Person" as Person
class "Member" as Member
class "BoardMember" as BoardMember
class "AAUOC" as Asociacion
class "Location" as Location

Event <|-- Conference
Event <|-- BoardMeeting
Event "0..*"--"1" Location : isLocated In
Event "0..*"--"0..*"Member : attendsTo

Person <|-- Member
Person "0..*"--"0..*" Conference: attendsTo

Member <|-- BoardMember

Asociacion o--"0..*" Person
Asociacion o--"0..*" Event
Asociacion o--"0..*" Location

BoardMeeting "0..*"--"0..*" BoardMember: attendsTo

class Asociacion{
newLocation(l : Location) : void
newEvent(e : Event) : void
newPerson(p : Person) : void
informEvent(e : Event) : void
register(m : Member,e : Event) : void
}

class Location{
description: String
addres: String
}

class Person{
name: String
}

class Event{
date: Date
description: String

assign(l_ Location):void
}

class Member{
e-mail: String
}

class Conference{
max_attendees: Interger
}
@enduml